name: Branch CI
run-name: ${{ github.actor }} is running ${{ github.repository }} CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  steampipe-legacy:
    uses: blinkops/blink-sdk/.github/workflows/plugin-ci.yaml@master
    with:
      run_number: ${{ github.run_number }}
      plugin_image_name: blink-steampipe
      branch_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run_tests: false
      run_make_cmd: false
      dockerfile_path: ./build/blink-steampipe/Dockerfile
    secrets: inherit
  steampipe-aws:
    uses: blinkops/blink-sdk/.github/workflows/plugin-ci.yaml@master
    with:
      run_number: ${{ github.run_number }}
      plugin_image_name: blink-steampipe-aws
      branch_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run_tests: false
      run_make_cmd: false
      dockerfile_path: ./build/blink-steampipe-aws/Dockerfile
    secrets: inherit
  steampipe-azure:
    uses: blinkops/blink-sdk/.github/workflows/plugin-ci.yaml@master
    with:
      run_number: ${{ github.run_number }}
      plugin_image_name: blink-steampipe-azure
      branch_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run_tests: false
      run_make_cmd: false
      dockerfile_path: ./build/blink-steampipe-azure/Dockerfile
    secrets: inherit
  steampipe-crowdstrike:
    uses: blinkops/blink-sdk/.github/workflows/plugin-ci.yaml@master
    with:
      run_number: ${{ github.run_number }}
      plugin_image_name: blink-steampipe-crowdstrike
      branch_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run_tests: false
      run_make_cmd: false
      dockerfile_path: ./build/blink-steampipe-crowdstrike/Dockerfile
    secrets: inherit
  steampipe-csv:
    uses: blinkops/blink-sdk/.github/workflows/plugin-ci.yaml@master
    with:
      run_number: ${{ github.run_number }}
      plugin_image_name: blink-steampipe-csv
      branch_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run_tests: false
      run_make_cmd: false
      dockerfile_path: ./build/blink-steampipe-csv/Dockerfile
    secrets: inherit
  steampipe-gcp:
    uses: blinkops/blink-sdk/.github/workflows/plugin-ci.yaml@master
    with:
      run_number: ${{ github.run_number }}
      plugin_image_name: blink-steampipe-gcp
      branch_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run_tests: false
      run_make_cmd: false
      dockerfile_path: ./build/blink-steampipe-gcp/Dockerfile
    secrets: inherit
  steampipe-github:
    uses: blinkops/blink-sdk/.github/workflows/plugin-ci.yaml@master
    with:
      run_number: ${{ github.run_number }}
      plugin_image_name: blink-steampipe-github
      branch_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run_tests: false
      run_make_cmd: false
      dockerfile_path: ./build/blink-steampipe-github/Dockerfile
    secrets: inherit
  steampipe-k8s:
    uses: blinkops/blink-sdk/.github/workflows/plugin-ci.yaml@master
    with:
      run_number: ${{ github.run_number }}
      plugin_image_name: blink-steampipe-k8s
      branch_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run_tests: false
      run_make_cmd: false
      dockerfile_path: ./build/blink-steampipe-k8s/Dockerfile
    secrets: inherit
  steampipe-oci:
    uses: blinkops/blink-sdk/.github/workflows/plugin-ci.yaml@master
    with:
      run_number: ${{ github.run_number }}
      plugin_image_name: blink-steampipe-oci
      branch_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run_tests: false
      run_make_cmd: false
      dockerfile_path: ./build/blink-steampipe-oci/Dockerfile
    secrets: inherit
  steampipe-terraform:
    uses: blinkops/blink-sdk/.github/workflows/plugin-ci.yaml@master
    with:
      run_number: ${{ github.run_number }}
      plugin_image_name: blink-steampipe-terraform
      branch_name: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
      run_tests: false
      run_make_cmd: false
      dockerfile_path: ./build/blink-steampipe-terraform/Dockerfile
    secrets: inherit
